### ISSUE TITLE
Request Update: .minigsf Implementation

### ISSUE THREAD

**Issue by Supremeoverlord3** [losnoco/multidumper#3]
Requesting that Gameboy Advance .minigsf files be implemented.

**Comment by kode54** [comment]
And what is hoped to be accomplished by that? Like USF, all the PCM audio is pre-mixed in software by the console code before it is output. So you'd really only be separating the GBC channels from the two PCM streams.

I could do it, though.

**Comment by Supremeoverlord3** [comment]
Thank you for your reply. What I wish to do is use Sidwiz to make oscilloscope videos of Gameboy Advance music. This software is dependent upon Multidumper, and the only other way is a ridiculously complicated process using agbplay which you have to practically hire a computer programmer to figure out.

**Comment by crs00** [comment]
> I can't even figure agbplay out; if you are going to upgrade multidumper with .minigsf, would you please inform me if you complete it? I would greatly appreciate it.

You split channels for songs by loading ROMs in agbplay.

**Comment by Supremeoverlord3** [comment]
I can't figure out how to do that. agbplay is so hard to run you have to be a computer programmer to figure it out.

**Comment by kode54** [comment]
I'm not adding it. You have to be a genius of a computer programmer to merge agbplay into this project.

**Comment by Supremeoverlord3** [comment]
Okay. How about SID implementation?
